CREATE DATABASE sample_database;

\c sample_database;

--CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
--    "MigrationId" character varying(150) NOT NULL,
--    "ProductVersion" character varying(32) NOT NULL,
--    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
--);

--START TRANSACTION;

CREATE TABLE "WorkItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(100) NOT NULL,
    "Completed" boolean NOT NULL,
    CONSTRAINT "PK_WorkItems" PRIMARY KEY ("Id")
);

--INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
--VALUES ('20250224150532_InitialCreate', '8.0.13');

--COMMIT;