CREATE DATABASE sample_database;

\c sample_database;


CREATE TABLE "WorkItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(100) NOT NULL,
    "Completed" boolean NOT NULL,
    CONSTRAINT "PK_WorkItems" PRIMARY KEY ("Id")
);